version: '3'
networks: 
  workers:
services:
  worker01:
    build: .
    env_file: ./.env
    command: node ./app
    networks:
      - workers
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  worker02:
    build: .
    env_file: ./.env
    command: node ./app
    networks:
      - workers
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  worker03:
    build: .
    env_file: ./.env
    command: node ./app
    networks:
      - workers
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules